#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="${PROJECT_DIR:-$(dirname "$SCRIPT_DIR")}"
UTIL_JSON="${UTIL_JSON:-/Users/wonheelee/Documents/Cursor/util/credentials/service-account.json}"

cd "$PROJECT_DIR"
if [[ -z "${GOOGLE_SERVICE_ACCOUNT_JSON:-}" ]]; then
  export GOOGLE_SERVICE_ACCOUNT_JSON="$(cat "$UTIL_JSON")"
fi

# 1) Extract updates (skip postprocess)
PYTHONUNBUFFERED=1 COMPETITOR_RUN_MODE=extract COMPETITOR_SKIP_POSTPROCESS=true \
  python3 -u scripts/update_competitor_sheets.py

# 2) Postprocess (chunked, per tab)
# 점핏
PYTHONUNBUFFERED=1 COMPETITOR_RUN_MODE=extract COMPETITOR_SKIP_EXTRACT=true \
  COMPETITOR_POSTPROCESS_ONLY_TAB="점핏_추출" COMPETITOR_POSTPROCESS_START_ROW=2 \
  COMPETITOR_POSTPROCESS_END_ROW=2002 COMPETITOR_POSTPROCESS_CHUNK_SIZE=250 \
  python3 -u scripts/update_competitor_sheets.py

# 원픽
PYTHONUNBUFFERED=1 COMPETITOR_RUN_MODE=extract COMPETITOR_SKIP_EXTRACT=true \
  COMPETITOR_POSTPROCESS_ONLY_TAB="원픽_추출" COMPETITOR_POSTPROCESS_START_ROW=2 \
  COMPETITOR_POSTPROCESS_END_ROW=2002 COMPETITOR_POSTPROCESS_CHUNK_SIZE=250 \
  python3 -u scripts/update_competitor_sheets.py

# 스마트리쿠르터
PYTHONUNBUFFERED=1 COMPETITOR_RUN_MODE=extract COMPETITOR_SKIP_EXTRACT=true \
  COMPETITOR_POSTPROCESS_ONLY_TAB="스마트리쿠르터_추출" COMPETITOR_POSTPROCESS_START_ROW=2 \
  COMPETITOR_POSTPROCESS_END_ROW=2002 COMPETITOR_POSTPROCESS_CHUNK_SIZE=250 \
  python3 -u scripts/update_competitor_sheets.py

# 리멤버
PYTHONUNBUFFERED=1 COMPETITOR_RUN_MODE=extract COMPETITOR_SKIP_EXTRACT=true \
  COMPETITOR_POSTPROCESS_ONLY_TAB="리멤버_추출" COMPETITOR_POSTPROCESS_START_ROW=2 \
  COMPETITOR_POSTPROCESS_END_ROW=2002 COMPETITOR_POSTPROCESS_CHUNK_SIZE=250 \
  python3 -u scripts/update_competitor_sheets.py

# 사람인(일반) - split ranges
PYTHONUNBUFFERED=1 COMPETITOR_RUN_MODE=extract COMPETITOR_SKIP_EXTRACT=true \
  COMPETITOR_POSTPROCESS_ONLY_TAB="사람인(일반)_추출" COMPETITOR_POSTPROCESS_START_ROW=2 \
  COMPETITOR_POSTPROCESS_END_ROW=2002 COMPETITOR_POSTPROCESS_CHUNK_SIZE=250 \
  python3 -u scripts/update_competitor_sheets.py

PYTHONUNBUFFERED=1 COMPETITOR_RUN_MODE=extract COMPETITOR_SKIP_EXTRACT=true \
  COMPETITOR_POSTPROCESS_ONLY_TAB="사람인(일반)_추출" COMPETITOR_POSTPROCESS_START_ROW=2002 \
  COMPETITOR_POSTPROCESS_END_ROW=4002 COMPETITOR_POSTPROCESS_CHUNK_SIZE=250 \
  python3 -u scripts/update_competitor_sheets.py

PYTHONUNBUFFERED=1 COMPETITOR_RUN_MODE=extract COMPETITOR_SKIP_EXTRACT=true \
  COMPETITOR_POSTPROCESS_ONLY_TAB="사람인(일반)_추출" COMPETITOR_POSTPROCESS_START_ROW=4002 \
  COMPETITOR_POSTPROCESS_END_ROW=6000 COMPETITOR_POSTPROCESS_CHUNK_SIZE=250 \
  python3 -u scripts/update_competitor_sheets.py

# 3) Master tabs (no freeze)
PYTHONUNBUFFERED=1 COMPETITOR_RUN_MODE=master COMPETITOR_MASTER_FREEZE=false \
  python3 -u scripts/update_competitor_sheets.py
